name: Publish
on: 
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . -t lgohr/squid-alpine:${{ github.sha }} -t lgohr/squid-alpine:latest
    - name: Login to Registry
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Push to Registry
      run: |
        docker push lgohr/squid-alpine:${{ github.sha }}
        docker push lgohr/squid-alpine:latest
    - name: Logout
      run: docker logout
